name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: false
        default: '0.8.0'
      publishReleases:
        description: 'Publish to Releases'
        required: false
        default: 'true'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Release Package
        run: |
          ./gradlew releaseProcessingLib --no-daemon

      - name: Build CUDA Windows-x86_64 Package
        run: |
          ./gradlew releaseProcessingLib -Pcuda -PjavacppPlatform=windows-x86_64 -PoutputNamePostfix=-cuda-windows-x86_64 --no-daemon

      - name: Build CUDA Linux-x86_64 Package
        run: |
          ./gradlew releaseProcessingLib -Pcuda -PjavacppPlatform=linux-x86_64 -PoutputNamePostfix=-cuda-linux-x86_64 --no-daemon

      - name: Build CUDA Linux-arm64 Package
        run: |
          ./gradlew releaseProcessingLib -Pcuda -PjavacppPlatform=linux-arm64 -PoutputNamePostfix=-cuda-linux-arm64 --no-daemon

      # upload dist
      - name: Upload binaries to release
        if: ${{ github.event.inputs.publishReleases == 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/*
          tag: "v${{ github.event.inputs.tag }}-alpha"
          release_name: "Version ${{ github.event.inputs.tag }}"
          body: "Prebuilt deep-vision-processing libs version ${{ github.event.inputs.tag }}."
          overwrite: true
          file_glob: true
          prerelease: true
